import type { Product } from "./products";

// Bahasa Melayu version of PRODUCTS in products.ts. Keep ids, categories and
// figures in step with the English file.
export const PRODUCTS_MS: Product[] = [
  {
    id: "aiko-comet-2u",
    category: "panels",
    brand: "AIKO",
    name: "AIKO Comet 2U 655W",
    tagline: "Panel sentuhan belakang serba hitam yang terus menjana walaupun sebahagian bumbung terlindung.",
    highlights: ["655 W setiap panel", "Kecekapan modul 24.2%", "Kekal menjana di bawah teduhan separa", "Waranti prestasi 30 tahun"],
    images: [{ src: "/products/aiko-comet-2u-crop.jpg", alt: "Panel solar serba hitam AIKO Comet 2U, depan dan belakang" }],
    overview:
      "Comet 2U menggunakan sel n-type ABC (sentuhan belakang penuh) AIKO, jadi tiada garisan perak di bahagian depan. Lebih banyak permukaan sel menyerap cahaya, bumbung kelihatan kemas, dan panel kekal lebih sejuk di bawah terik matahari.",
    features: ["Sel sentuhan belakang n-type ABC, separuh potong, 144 setiap panel", "Kuasa terkadar 655 W pada kecekapan 24.2%", "Terus berfungsi walaupun sesetengah sel terlindung", "Pemenang anugerah reka bentuk Red Dot 2023"],
    benefits: ["Lebih banyak tenaga dari ruang bumbung yang sama", "Daun, tiang dan dinding jiran kurang menjejaskan penjanaan", "Kekal sejuk dalam cuaca panas Malaysia, jadi penjanaan kurang menurun pada tengah hari", "Bumbung serba hitam yang kemas tanpa garisan grid"],
    specs: [
      { label: "Model", value: "AIKO-G655-MCH72Mw" },
      { label: "Jenis sel", value: "n-type, sentuhan belakang ABC, separuh sel" },
      { label: "Saiz wafer", value: "182 mm" },
      { label: "Bilangan sel", value: "144" },
      { label: "Kuasa terkadar", value: "655 W" },
      { label: "Kecekapan modul", value: "24.2%" },
      { label: "Waranti produk", value: "15 tahun" },
      { label: "Waranti prestasi", value: "30 tahun" },
    ],
    applications: ["Bumbung rumah dengan ruang terhad", "Bumbung yang terlindung oleh pokok atau dinding", "Bumbung komersial"],
    faq: [
      { q: "Sejauh mana teduhan menjejaskannya?", a: "Dalam ujian teduhan AIKO dengan dua sel terlindung, Comet mengekalkan 94.3% penjanaan berbanding 65.9% bagi panel tradisional." },
      { q: "Apakah yang dilindungi oleh waranti?", a: "15 tahun untuk produk dan 30 tahun untuk penjanaan kuasa." },
    ],
  },
  {
    id: "sigen-hybrid-inverter",
    category: "inverters",
    brand: "Sigenergy",
    name: "Inverter Hibrid Sigen",
    tagline: "Inverter nipis tanpa kipas. Mulakan dengan solar sekarang, tambah bateri bila-bila anda bersedia.",
    highlights: ["Kecekapan maksimum 99.0%", "Senyap pada 25 dB, tiada kipas", "Kedap IP66", "Sedia untuk bateri"],
    images: [{ src: "/products/sigen-hybrid-inverter.webp", alt: "Inverter hibrid Sigenergy, panel depan putih" }],
    overview:
      "Inverter hibrid Sigenergy (SP2 satu fasa, TP2 tiga fasa) menggunakan komponen silikon karbida untuk mencapai kecekapan 99.0% dalam badan tuangan logam setebal 99 mm. Tiada kipas, jadi ia beroperasi dengan senyap di sebelah rumah.",
    features: ["Elektronik kuasa silikon karbida (SiC)", "Penyejukan tanpa kipas, 25 dB", "Badan tuangan logam nipis 99 mm", "Aplikasi mySIGEN dengan kemas kini aliran tenaga setiap 10 saat"],
    benefits: ["Kurang tenaga hilang antara panel dan soket anda", "Cukup senyap untuk dipasang berhampiran ruang kediaman", "Tidak perlu tukar inverter apabila menambah Bateri Sigen", "Lihat ke mana setiap watt pergi, terus di telefon anda"],
    specs: [
      { label: "Model", value: "SP2 (satu fasa), TP2 (tiga fasa)" },
      { label: "Kecekapan maksimum", value: "99.0%" },
      { label: "Bunyi", value: "25 dB, tanpa kipas" },
      { label: "Ketebalan badan", value: "99 mm" },
      { label: "Perlindungan", value: "IP66 habuk dan pancutan air" },
      { label: "Suhu operasi", value: "-30°C hingga 60°C" },
      { label: "Waranti", value: "10 tahun" },
    ],
    applications: ["Rumah yang mahu solar dahulu, storan kemudian", "Pemasangan dinding berhampiran bilik tidur atau anjung", "Pemasangan luar yang terdedah kepada hujan"],
    faq: [
      { q: "Bolehkah saya tambah bateri kemudian?", a: "Boleh. Mulakan dengan inverter sahaja dan sambungkan Bateri Sigen bila-bila masa untuk menambah storan dan kuasa sandaran." },
      { q: "Bagaimana saya menyemak prestasi sistem?", a: "Aplikasi mySIGEN memaparkan aliran tenaga masa nyata, graf dan laporan boleh muat turun, dan Sigen AI Mode boleh menjadualkan pengecasan mengikut cuaca dan tarif." },
    ],
  },
  {
    id: "foxess-hybrid-inverter",
    category: "inverters",
    brand: "FoxESS",
    name: "Inverter Hibrid FoxESS",
    tagline: "Inverter hibrid yang tahan lasak dengan kuasa sandaran dan ruang untuk berkembang.",
    highlights: ["IP65, penyejukan semula jadi", "Output sandaran EPS", "Sehingga 10 unit selari", "Waranti 10 tahun"],
    images: [{ src: "/products/foxess-hybrid-inverter.webp", alt: "Inverter hibrid FoxESS dengan panel paparan" }],
    overview:
      "Inverter hibrid voltan tinggi yang mengurus panel, bateri dan grid dalam satu unit. Pemasangan pasang-dan-guna dengan perlindungan fius terbina dalam, dan boleh digandingkan dengan lebih banyak unit apabila keperluan anda bertambah.",
    features: ["Input bateri voltan tinggi", "Fungsi EPS untuk kuasa sandaran semasa gangguan bekalan", "Pemasangan pasang-dan-guna dengan perlindungan fius terbina dalam", "Pemantauan jarak jauh melalui portal web dan aplikasi FoxCloud"],
    benefits: ["Peralatan penting terus berfungsi apabila grid terputus", "Tambah unit untuk kembangkan, bukan menggantikan", "Sesuai untuk pemasangan luar", "Tetapan dan data boleh diakses dari mana-mana"],
    specs: [
      { label: "Penyejukan", value: "Perolakan semula jadi" },
      { label: "Perlindungan", value: "IP65" },
      { label: "Selari atas grid", value: "2 hingga 10 unit" },
      { label: "Selari luar grid", value: "2 hingga 7 unit" },
      { label: "Pengembangan bateri", value: "Sehingga 18 bateri bersiri" },
      { label: "Waranti", value: "10 tahun" },
    ],
    applications: ["Rumah yang mahukan sandaran semasa gangguan bekalan", "Rumah besar dan perniagaan kecil", "Digandingkan dengan bateri FoxESS EP"],
    faq: [
      { q: "Adakah lampu rumah saya kekal menyala semasa bekalan terputus?", a: "Dengan bateri disambungkan, output EPS membekalkan kuasa kepada litar yang disambung kepadanya semasa grid terputus." },
      { q: "Bolehkah sistem ini dikembangkan kemudian?", a: "Boleh. Tambah bateri, atau jalankan 2 hingga 10 inverter secara selari atas grid." },
    ],
  },
  {
    id: "foxess-ep-battery",
    category: "batteries",
    brand: "FoxESS",
    name: "Bateri FoxESS EP6 / EP12",
    tagline: "Bateri modular yang boleh disusun secara selari apabila penggunaan anda bertambah.",
    highlights: ["Kedalaman nyahcas 90%", "EP6 hingga 23.04 kWh", "EP12 hingga 46.08 kWh", "Pemasangan lantai atau dinding"],
    images: [
      { src: "/products/foxess-ep6.png", alt: "Bateri FoxESS EP6, unit putih tegak" },
      { src: "/products/foxess-ep12.png", alt: "Bateri FoxESS EP12, unit putih lebar" },
    ],
    overview:
      "EP6 dan EP12 ialah reka bentuk yang sama dalam dua saiz. Tambah lebih banyak unit secara selari untuk membina storan sehingga 23.04 kWh dengan EP6 atau 46.08 kWh dengan EP12.",
    features: ["Reka bentuk modular, unit disambung secara selari", "Kedalaman nyahcas boleh guna 90%", "Pemasangan lantai atau dinding", "Perlindungan habuk dan air IP65"],
    benefits: ["Beli kapasiti yang anda perlukan hari ini, tambah kemudian", "Gunakan hampir semua tenaga yang disimpan", "Muat di dinding garaj atau sudut lantai", "Sesuai untuk pemasangan luar"],
    specs: [
      { label: "Saiz EP6 (L×T×D)", value: "380 × 640 × 185 mm" },
      { label: "Berat EP6", value: "51 kg" },
      { label: "Kapasiti maksimum EP6", value: "23.04 kWh" },
      { label: "Saiz EP12 (L×T×D)", value: "710 × 640 × 185 mm" },
      { label: "Berat EP12", value: "98 kg" },
      { label: "Kapasiti maksimum EP12", value: "46.08 kWh" },
      { label: "Kedalaman nyahcas", value: "90%" },
      { label: "Waranti", value: "10 tahun" },
    ],
    applications: ["Menyimpan tenaga solar tengah hari untuk waktu malam", "Sandaran bersama Inverter Hibrid FoxESS", "Pemasangan luar atau di garaj"],
    faq: [
      { q: "EP6 atau EP12?", a: "Teknologi yang sama. EP12 menyimpan lebih banyak setiap unit, EP6 lebih kecil dan ringan (51 kg berbanding 98 kg). Kami saiz berdasarkan bil anda." },
      { q: "Bolehkah saya tambah lebih banyak bateri kemudian?", a: "Boleh, lebih banyak unit disambung secara selari sehingga kapasiti maksimum setiap model." },
    ],
  },
  {
    id: "sigenstor-neo",
    category: "batteries",
    brand: "Sigenergy",
    name: "SigenStor Neo",
    tagline: "Lima sistem dalam satu kabinet: inverter, bateri dan sandaran, disusun kemas.",
    highlights: ["Kabinet 5-dalam-1", "Tukar ke sandaran dalam 0 ms", "4 MPPT untuk bumbung kompleks", "Campur modul lama dan baharu"],
    images: [{ src: "/products/sigenstor-neo.png", alt: "Kabinet bateri bertingkat SigenStor Neo" }],
    overview:
      "SigenStor Neo menggabungkan pengurus tenaga, inverter PV, penukar bateri, pek bateri dan modul sandaran dalam satu susunan padat. Tambah modul bateri bila-bila masa: pengoptimum terbina dalam membolehkan pek lama dan baharu berfungsi bersama.",
    features: ["EMS, inverter PV, PCS bateri, bateri dan sandaran dalam satu unit", "Modul boleh disusun dengan penyambung pantas", "Port sandaran dan port pintar untuk seluruh rumah", "Sel bersaiz besar dengan pemantauan berterusan dan pencegahan kebakaran"],
    benefits: ["Satu kabinet kemas menggantikan beberapa kotak di dinding", "Peralatan tidak terasa apabila grid terputus", "Tambah storan tanpa menukar modul lama", "Serasi dengan pengecas EV, penjana atau inverter jenama lain"],
    specs: [
      { label: "Integrasi", value: "5-dalam-1" },
      { label: "Pertukaran sandaran", value: "0 ms gangguan di sisi beban" },
      { label: "MPPT", value: "4" },
      { label: "Perlindungan", value: "IP66" },
      { label: "Pengembangan", value: "Modular, pek lama dan baharu boleh dicampur" },
      { label: "Waranti", value: "10 tahun" },
    ],
    applications: ["Sandaran seluruh rumah", "Mengecas EV dengan tenaga solar", "Menambah storan pada sistem solar sedia ada"],
    faq: [
      { q: "Saya sudah ada solar dengan inverter lain. Bolehkah ia digunakan?", a: "Boleh. SigenStor Neo serasi dengan inverter pihak ketiga, jadi ia boleh dipasang tambah." },
      { q: "Apa berlaku semasa bekalan elektrik terputus?", a: "Beban pada port sandaran bertukar dengan 0 ms gangguan, jadi lampu dan peti sejuk terus berfungsi." },
    ],
  },
];
