import type { Product } from "./products";

// Simplified Chinese version of PRODUCTS in products.ts. Keep ids, categories
// and figures in step with the English file.
export const PRODUCTS_CN: Product[] = [
  {
    id: "aiko-comet-2u",
    category: "panels",
    brand: "AIKO",
    name: "AIKO Comet 2U 655W",
    tagline: "全黑背接触太阳能板，屋顶部分被遮挡时依然持续发电。",
    highlights: ["每片 655 W", "组件效率 24.2%", "部分遮挡下仍保持输出", "30 年功率质保"],
    images: [{ src: "/products/aiko-comet-2u-crop.jpg", alt: "AIKO Comet 2U 全黑太阳能板正面与背面" }],
    overview:
      "Comet 2U 采用 AIKO 的 n 型 ABC（全背接触）电池，正面没有银色栅线。每片电池有更多面积吸收阳光，屋顶外观更整洁，在强烈日照下温度也更低。",
    features: ["n 型 ABC 背接触电池，半片设计，每片 144 片电池", "额定功率 655 W，效率 24.2%", "部分电池被遮挡时仍能工作", "2023 年红点设计奖得主"],
    benefits: ["同样的屋顶面积，发更多电", "树叶、电线杆和邻墙对发电量的影响更小", "在马来西亚高温下保持较低温度，中午发电量下降更少", "全黑屋顶，看不到栅线，整洁美观"],
    specs: [
      { label: "型号", value: "AIKO-G655-MCH72Mw" },
      { label: "电池类型", value: "n 型，ABC 背接触，半片" },
      { label: "硅片尺寸", value: "182 mm" },
      { label: "电池片数", value: "144" },
      { label: "额定功率", value: "655 W" },
      { label: "组件效率", value: "24.2%" },
      { label: "产品质保", value: "15 年" },
      { label: "功率质保", value: "30 年" },
    ],
    applications: ["空间有限的住宅屋顶", "有树木或墙体遮挡的屋顶", "商业屋顶"],
    faq: [
      { q: "遮挡对它的影响有多大？", a: "在 AIKO 的遮挡测试中，两处遮挡时 Comet 仍保持 94.3% 的输出，传统太阳能板只有 65.9%。" },
      { q: "质保涵盖什么？", a: "产品本身 15 年质保，发电功率 30 年质保。" },
    ],
  },
  {
    id: "sigen-hybrid-inverter",
    category: "inverters",
    brand: "Sigenergy",
    name: "Sigen 混合逆变器",
    tagline: "纤薄无风扇逆变器。现在先装太阳能，准备好时再加电池。",
    highlights: ["最高效率 99.0%", "无风扇，仅 25 dB", "IP66 密封", "可随时加装电池"],
    images: [{ src: "/products/sigen-hybrid-inverter.webp", alt: "Sigenergy 混合逆变器白色正面" }],
    overview:
      "Sigenergy 混合逆变器（SP2 单相，TP2 三相）采用碳化硅元件，在 99 mm 厚的压铸金属机身内实现 99.0% 效率。没有风扇，安装在屋旁也很安静。",
    features: ["碳化硅（SiC）功率电子元件", "无风扇散热，25 dB", "99 mm 纤薄压铸金属机身", "mySIGEN 应用程序，每 10 秒更新能量流"],
    benefits: ["从太阳能板到插座之间损耗更少", "够安静，可安装在起居空间附近", "日后加装 Sigen 电池无需更换逆变器", "在手机上看清每一瓦电的去向"],
    specs: [
      { label: "型号", value: "SP2（单相），TP2（三相）" },
      { label: "最高效率", value: "99.0%" },
      { label: "噪音", value: "25 dB，无风扇" },
      { label: "机身厚度", value: "99 mm" },
      { label: "防护等级", value: "IP66 防尘防喷水" },
      { label: "工作温度", value: "-30°C 至 60°C" },
      { label: "质保", value: "10 年" },
    ],
    applications: ["先装太阳能、之后再加储能的家庭", "安装在卧室或露台附近的墙上", "会被雨淋的户外安装"],
    faq: [
      { q: "以后可以加电池吗？", a: "可以。先单独安装逆变器，之后随时接上 Sigen 电池，即可增加储能和备用电源。" },
      { q: "我怎么查看系统运行情况？", a: "mySIGEN 应用程序显示实时能量流、图表和可下载报告，Sigen AI 模式还能根据天气和电价安排充电。" },
    ],
  },
  {
    id: "foxess-hybrid-inverter",
    category: "inverters",
    brand: "FoxESS",
    name: "FoxESS 混合逆变器",
    tagline: "可靠耐用的混合逆变器，具备备用电源，还有扩展空间。",
    highlights: ["IP65，自然散热", "EPS 备用电源输出", "最多 10 台并联运行", "10 年质保"],
    images: [{ src: "/products/foxess-hybrid-inverter.webp", alt: "带显示面板的 FoxESS 混合逆变器" }],
    overview: "一台高压混合逆变器，统一管理太阳能板、电池和电网。即插即用安装，内置保险丝保护，需求增加时可并联更多机组。",
    features: ["高压电池输入", "EPS 功能，停电时提供备用电源", "即插即用安装，内置保险丝保护", "通过网页平台和 FoxCloud 应用程序远程监控"],
    benefits: ["电网断电时重要电器继续运行", "增加机组即可扩容，无需更换", "适合户外安装", "随时随地查看设置和数据"],
    specs: [
      { label: "散热方式", value: "自然对流" },
      { label: "防护等级", value: "IP65" },
      { label: "并网并联", value: "2 至 10 台" },
      { label: "离网并联", value: "2 至 7 台" },
      { label: "电池扩展", value: "最多 18 个电池串联" },
      { label: "质保", value: "10 年" },
    ],
    applications: ["需要停电备用的家庭", "较大的住宅和小型企业", "搭配 FoxESS EP 电池"],
    faq: [
      { q: "停电时能保持家里有电吗？", a: "接上电池后，电网断电期间 EPS 输出会为接入的线路供电。" },
      { q: "系统以后可以扩展吗？", a: "可以。可以加装电池，或在并网状态下并联 2 至 10 台逆变器。" },
    ],
  },
  {
    id: "foxess-ep-battery",
    category: "batteries",
    brand: "FoxESS",
    name: "FoxESS EP6 / EP12 电池",
    tagline: "模块化电池，用电增加时可并联叠加。",
    highlights: ["放电深度 90%", "EP6 可扩展至 23.04 kWh", "EP12 可扩展至 46.08 kWh", "落地或壁挂安装"],
    images: [
      { src: "/products/foxess-ep6.png", alt: "FoxESS EP6 电池，直立白色机身" },
      { src: "/products/foxess-ep12.png", alt: "FoxESS EP12 电池，宽体白色机身" },
    ],
    overview: "EP6 和 EP12 是同一设计的两种尺寸。并联更多机组，EP6 最高可达 23.04 kWh，EP12 最高可达 46.08 kWh。",
    features: ["模块化设计，机组并联连接", "可用放电深度 90%", "落地或壁挂安装", "IP65 防尘防水"],
    benefits: ["今天买需要的容量，以后再加", "储存的电几乎全部可用", "可装在车库墙上或地面角落", "适合户外安装"],
    specs: [
      { label: "EP6 尺寸（宽×高×深）", value: "380 × 640 × 185 mm" },
      { label: "EP6 重量", value: "51 kg" },
      { label: "EP6 最大容量", value: "23.04 kWh" },
      { label: "EP12 尺寸（宽×高×深）", value: "710 × 640 × 185 mm" },
      { label: "EP12 重量", value: "98 kg" },
      { label: "EP12 最大容量", value: "46.08 kWh" },
      { label: "放电深度", value: "90%" },
      { label: "质保", value: "10 年" },
    ],
    applications: ["把中午的太阳能留到晚上用", "搭配 FoxESS 混合逆变器作备用电源", "户外或车库安装"],
    faq: [
      { q: "选 EP6 还是 EP12？", a: "技术相同。EP12 单机容量更大，EP6 更小更轻（51 kg 对 98 kg）。我们会根据您的电费单来配置。" },
      { q: "以后可以加更多电池吗？", a: "可以，更多机组可并联连接，直至各型号的最大容量。" },
    ],
  },
  {
    id: "sigenstor-neo",
    category: "batteries",
    brand: "Sigenergy",
    name: "SigenStor Neo",
    tagline: "一个机柜集成五大系统：逆变器、电池和备用电源，整齐叠放。",
    highlights: ["五合一机柜", "0 ms 切换至备用电源", "4 路 MPPT 适应复杂屋顶", "新旧模块可混用"],
    images: [{ src: "/products/sigenstor-neo.png", alt: "SigenStor Neo 叠放式电池机柜" }],
    overview:
      "SigenStor Neo 把能源管理系统、光伏逆变器、电池变流器、电池组和备用模块集成在一个紧凑的叠放机柜中。随时加装电池模块：内置优化器让新旧电池并肩运行。",
    features: ["EMS、光伏逆变器、电池 PCS、电池和备用模块合为一体", "可叠放模块，配快速接头", "备用端口和智能端口覆盖全屋", "大容量电芯，持续监测并防火"],
    benefits: ["一个整洁的机柜，取代墙上的多个箱子", "电网断电时电器毫无察觉", "扩充储能无需替换旧模块", "兼容您的电动车充电器、发电机或其他品牌逆变器"],
    specs: [
      { label: "集成度", value: "五合一" },
      { label: "备用切换", value: "负载端 0 ms 中断" },
      { label: "MPPT 路数", value: "4" },
      { label: "防护等级", value: "IP66" },
      { label: "扩展", value: "模块化，新旧电池可混用" },
      { label: "质保", value: "10 年" },
    ],
    applications: ["全屋备用电源", "用太阳能为电动车充电", "为现有太阳能系统加装储能"],
    faq: [
      { q: "我已经装了其他品牌逆变器的太阳能，能用吗？", a: "能。SigenStor Neo 兼容第三方逆变器，可以直接加装。" },
      { q: "停电时会怎样？", a: "接在备用端口上的负载以 0 ms 中断切换，电灯和冰箱都不会断电。" },
    ],
  },
];
